//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BaseDatos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CocheEntities3 : DbContext
    {
        public CocheEntities3()
            : base("name=CocheEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coche> Coche { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<Modelo> Modelo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }

        public System.Data.Entity.DbSet<BaseDatos.Models.ViewModel.Join> UsuarioMasCoches { get; set; }
    }
}
